version: '3.8'

services:
  hr-chatbot:
    build: .
    ports:
      - "8000:8000"  # Backend API
      - "8501:8501"  # Streamlit Frontend
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./dataset:/app/dataset:ro  # Read-only dataset mount
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: hr-chatbot-network
