# render.yaml - Blueprint for deploying the HR Chatbot on Render

services:
  # Backend Service (FastAPI)
  - type: web
    name: backend
    env: docker
    repo: https://github.com/sujal-thakkar/hr-query-chatbot # <-- IMPORTANT: Update this to your repo URL
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /health
    envVars:
      # Declare these keys. Their values will be set in Render's dashboard.
      # Render will automatically treat them as secrets.
      - key: GEMINI_API_KEY
        sync: false # This tells Render the value is not in the repo, but will be set in the UI
      - key: OPENAI_API_KEY
        sync: false # This tells Render the value is not in the repo, but will be set in the UI
      # Cache backend (auto|redis|memory).
      - key: CACHE_BACKEND
        value: auto

  # Frontend Service (Streamlit)
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/sujal-thakkar/hr-query-chatbot # <-- IMPORTANT: Update this to your repo URL
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: API_BASE
        value: http://${backend.host}:${backend.port} # Correct way to reference backend service
