# Example Streamlit secrets (DO NOT commit real backend URL in production)
# Copy to .streamlit/secrets.toml for local dev only.
# Public deployment should rely on environment variables:
#   PUBLIC_BACKEND_URL=https://backend-xxxx.onrender.com

API_BASE = "http://localhost:8000"  # Local dev fallback
